services:
  ohrwurm:
    container_name: ohrwurm
    image: jheuel/ohrwurm:latest@sha256:b5e0fbc40ed86820eba8673bb5a97ad6ce53f27a1c557e46515cabce35199296
    # build: .
    restart: unless-stopped
    volumes:
      - ./data:/data
    env_file:
      - .env
